package com.QA.TestApp.Utilities;

import org.openqa.selenium.support.PageFactory;

import com.QA.TestApp.Pages.MOBILE.CalcPage;
import com.QA.TestApp.Pages.MOBILE.MyAccount_TCPHomePage_Mobile;
import com.QA.TestApp.Pages.MOBILE.MyOffers_Mobile;
import com.QA.TestApp.Pages.MOBILE.SwtTcpHomePage_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_AccountListPage_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_AccountTransferPage_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_AddCardPage_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_AddressChoosePage_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_AddressPage_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_BP_FetchBillAndBillersPage_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_BP_Payments_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_BP_RecentBillsAndCategoryPage_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_ChangePasswordPage_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_Channels_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_CromaCardPage_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_EnterAddressManuallyPage_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_FSClaimsPage_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_FSLendingPage_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_FSMyPlans_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_FSUploadDocPage_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_FinancialServices_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_GetCurrentLocationPage_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_GoogleSearchAddressPage_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_HomeInsurancePage_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_HomePage_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_InsuranceCancellation_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_InsuranceStatus_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_MAHDselectionPage_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_MANewConnectionPaymentsPage_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_MASelectChannels_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_MASelectlanguagesPage_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_ManageBanksPage_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_ManageFavoritesPage_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_ManageTransactionLimitPage_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_MenuPage_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_MultitenderPage_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_MyQRPage_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_OrderDetails_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_OrderHistory_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_OtherPage_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_PayToSelfPage_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_PaymentCards_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_PaymentMethodPage_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_PaymentsPage_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_ProfilePage_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_ReferFriendPage_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_ReferNonTCPContactsPage_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_RequestMoneyPage_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_SLPElectronicsPage_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_SearchPage_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_SecurePage_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_Signup_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_TCPCardPage_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_TataPayChannelPage_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_TataSkyRegisterPage_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_TransactionStatus_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_Transaction_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_UPIRegistrationPage_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_UPI_ApprovePage_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_UPI_MandatePage_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_UPI_SettingsPage_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_UPI_TransHistoryPage_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_UniversalCart_Mobile_Page;
import com.QA.TestApp.Pages.MOBILE.TDL_VaultPage_Mobile;
import com.QA.TestApp.Pages.WEB.B2BLogin;
import com.QA.TestApp.Pages.WEB.B2BPage2;
import com.QA.TestApp.Pages.WEB.Gmail;
import com.QA.TestApp.Pages.WEB.MyOffersPage;
import com.QA.TestApp.Pages.WEB.OfferDetailsPage;
import com.QA.TestApp.Pages.WEB.PaymentCards;
import com.QA.TestApp.Pages.WEB.Qmin_CRM_Mobile_Element;
import com.QA.TestApp.Pages.WEB.SwtTcpHomePage;
import com.QA.TestApp.Pages.WEB.TDL_AccountListPage;
import com.QA.TestApp.Pages.WEB.TDL_AddCardPage;
import com.QA.TestApp.Pages.WEB.TDL_AddressChoosePage;
import com.QA.TestApp.Pages.WEB.TDL_AddressPage;
import com.QA.TestApp.Pages.WEB.TDL_CRM_DetailsPage;
import com.QA.TestApp.Pages.WEB.TDL_Capillary_API_Page;
import com.QA.TestApp.Pages.WEB.TDL_CardProtectionJourneyPage;
import com.QA.TestApp.Pages.WEB.TDL_ChangePasswordPage;
import com.QA.TestApp.Pages.WEB.TDL_ChannelsPage;
import com.QA.TestApp.Pages.WEB.TDL_CromaCardPage;
import com.QA.TestApp.Pages.WEB.TDL_CromaLoginPage;
import com.QA.TestApp.Pages.WEB.TDL_EnterAddressManuallyPage;
import com.QA.TestApp.Pages.WEB.TDL_FSDocUploadPage;
import com.QA.TestApp.Pages.WEB.TDL_GetCurrentLocationPage;
import com.QA.TestApp.Pages.WEB.TDL_GoogleSearchAddressPage;
import com.QA.TestApp.Pages.WEB.TDL_HomeInsuranceJourneyPage;
import com.QA.TestApp.Pages.WEB.TDL_HomePage;
import com.QA.TestApp.Pages.WEB.TDL_IHCLCardPage;
import com.QA.TestApp.Pages.WEB.TDL_LegalPage;
import com.QA.TestApp.Pages.WEB.TDL_LendingPage;
import com.QA.TestApp.Pages.WEB.TDL_MABoxgradeHomePage;
import com.QA.TestApp.Pages.WEB.TDL_MAChannelsOptionPage;
import com.QA.TestApp.Pages.WEB.TDL_MACromaHomePage;
import com.QA.TestApp.Pages.WEB.TDL_MACromaSearchProductPage;
import com.QA.TestApp.Pages.WEB.TDL_MAHDselectionPage;
import com.QA.TestApp.Pages.WEB.TDL_MANewConnectionPaymentsPage;
import com.QA.TestApp.Pages.WEB.TDL_MAOPELPaymentsPage;
import com.QA.TestApp.Pages.WEB.TDL_MAPaymentConnectionPage;
import com.QA.TestApp.Pages.WEB.TDL_MAQuickRechargeHomePage;
import com.QA.TestApp.Pages.WEB.TDL_MAQuickRechargeOfferPage;
import com.QA.TestApp.Pages.WEB.TDL_MARegisterPage;
import com.QA.TestApp.Pages.WEB.TDL_MASelectChannels;
import com.QA.TestApp.Pages.WEB.TDL_MASelectlanguagesPage;
import com.QA.TestApp.Pages.WEB.TDL_MAShowcasePage;
import com.QA.TestApp.Pages.WEB.TDL_MATataSkyHomePage;
import com.QA.TestApp.Pages.WEB.TDL_MultitenderPage;
import com.QA.TestApp.Pages.WEB.TDL_OrderDetailsPage;
import com.QA.TestApp.Pages.WEB.TDL_OrderHistoryPage;
import com.QA.TestApp.Pages.WEB.TDL_PayBillPage;
import com.QA.TestApp.Pages.WEB.TDL_PaymentsPage;
import com.QA.TestApp.Pages.WEB.TDL_PersonalLoanPage;
import com.QA.TestApp.Pages.WEB.TDL_ProfilePage;
import com.QA.TestApp.Pages.WEB.TDL_ReferaFriendPage;
import com.QA.TestApp.Pages.WEB.TDL_SLPElectronicsPage;
import com.QA.TestApp.Pages.WEB.TDL_SSO;
import com.QA.TestApp.Pages.WEB.TDL_SearchPage;
import com.QA.TestApp.Pages.WEB.TDL_SecurePage;
import com.QA.TestApp.Pages.WEB.TDL_Signup;
import com.QA.TestApp.Pages.WEB.TDL_TCPCardPage;
import com.QA.TestApp.Pages.WEB.TDL_TransactionPage;
import com.QA.TestApp.Pages.WEB.TDL_TransactionStatus;
import com.QA.TestApp.Pages.WEB.TDL_UniversalCartPage;
import com.QA.TestApp.Pages.WEB.TDL_VaultPage;
import com.QA.TestApp.Pages.WEB.TcpHomePageMyAccount;
import com.QA.TestApp.Pages.WEB.TDL_IHCLLoginPage;
import com.QA.TestApp.Pages.MOBILE.NCOM_HomePage_Mobile;
import com.QA.TestApp.Pages.MOBILE.NCOM_Electronics_CLP_Page_Mobile;
import com.QA.TestApp.Pages.MOBILE.NCOM_PDP_Page_Mobile;
import com.QA.TestApp.Pages.MOBILE.NCOM_PLP_Page_Mobile;
import com.QA.TestApp.Pages.WEB.NCOM_HomePage_Web;
import com.QA.TestApp.Pages.WEB.NCOM_Electronics_CLP_Web;
import com.QA.TestApp.Pages.WEB.NCOM_PDP_Web;
import com.QA.TestApp.Pages.WEB.NCOM_PLP_Web;
import com.QA.TestApp.Pages.WEB.TCP_Performance;
import com.QA.TestApp.Pages.MOBILE.NCOM_Cart_Page_Mobile;
import com.QA.TestApp.Pages.WEB.TDL_SLPCultFit;
import com.QA.TestApp.Pages.MOBILE.TDL_SLPCultFit_Mobile;
import com.QA.TestApp.Pages.MOBILE.TDL_SLPElectronics_FlutterPage_Mobile;
import com.QA.TestApp.Pages.MOBILE.BB_TestCases;
import com.QA.TestApp.Pages.MOBILE.Rewards_And_Benifits;

public class PageInitiation {
	
	public static ThreadLocal<B2BLogin> B2BLogin = new ThreadLocal<>();
	public static ThreadLocal<B2BPage2> B2BPage2 = new ThreadLocal<>();
	public static ThreadLocal<CalcPage> CalcPage = new ThreadLocal<>();
	public static ThreadLocal<TDL_Signup> TdlSignUp = new ThreadLocal<>();
	public static ThreadLocal<TDL_HomePage> TdlHomePage = new ThreadLocal<>();
	public static ThreadLocal<TDL_VaultPage> TdlVaultPage = new ThreadLocal<>();
	public static ThreadLocal<TDL_TCPCardPage> TdlTcpCard = new ThreadLocal<>();
	public static ThreadLocal<TDL_CromaCardPage> TdlCromaCard = new ThreadLocal<>();
	public static ThreadLocal<TDL_Signup_Mobile> TdlSignUpMobile = new ThreadLocal<>();
	public static ThreadLocal<MyOffersPage> MyOffersPage = new ThreadLocal<>();
	public static ThreadLocal<MyOffers_Mobile> MyOffers_Mobile = new ThreadLocal<>();
	public static ThreadLocal<OfferDetailsPage> OfferDetailsPage = new ThreadLocal<>();
	public static ThreadLocal<TDL_HomePage_Mobile> TdlHomeMobile = new ThreadLocal<>();
	public static ThreadLocal<TDL_VaultPage_Mobile> TdlVaultMobile = new ThreadLocal<>();
	public static ThreadLocal<TDL_TCPCardPage_Mobile> TdlTCPCardMobile = new ThreadLocal<>();
	public static ThreadLocal<TDL_CromaCardPage_Mobile> TdlCromaCardMobile = new ThreadLocal<>();
	public static ThreadLocal<TDL_SearchPage_Mobile> TdlSearchPage_Mobile = new ThreadLocal<>();
	public static ThreadLocal<TDL_AccountListPage_Mobile> TdlAccountListPage_Mobile = new ThreadLocal<>();
	public static ThreadLocal<TDL_AccountListPage> TdlAccountListPage = new ThreadLocal<>();
	public static ThreadLocal<TDL_SearchPage> TdlSearchPage = new ThreadLocal<>();
	public static ThreadLocal<TDL_IHCLCardPage> TdlIhclCard = new ThreadLocal<>();
	public static ThreadLocal<TDL_PaymentsPage> TdlPaymentsPage = new ThreadLocal<>();
	public static ThreadLocal<TDL_MultitenderPage> TdlMultitenderPage = new ThreadLocal<>();
	public static ThreadLocal<TDL_TransactionStatus> TdlTransactionStatus = new ThreadLocal<>();
	public static ThreadLocal<TDL_SecurePage> TdlSecurePage = new ThreadLocal<>();
	public static ThreadLocal<TDL_AddCardPage> TdlAddCardPage = new ThreadLocal<>();
	public static ThreadLocal<TDL_PaymentMethodPage_Mobile> TDLPaymentMethodPage_Mobile = new ThreadLocal<>();
	public static ThreadLocal<TDL_AddCardPage_Mobile> TdlAddCardPage_Mobile = new ThreadLocal<>();
	public static ThreadLocal<TDL_SecurePage_Mobile> TdlSecurePage_Mobile = new ThreadLocal<>();
	public static ThreadLocal<TDL_MultitenderPage_Mobile> TdlMultitenderPage_Mobile = new ThreadLocal<>();
	public static ThreadLocal<TDL_PaymentsPage_Mobile> TdlPaymentsPage_Mobile = new ThreadLocal<>();
	public static ThreadLocal<TDL_TransactionStatus_Mobile> TdlTransactionStatus_Mobile = new ThreadLocal<>();
	public static ThreadLocal<TDL_OtherPage_Mobile> TdlOtherPage_Mobile = new ThreadLocal<>();
	public static ThreadLocal<TDL_ProfilePage> TdlProfilePage = new ThreadLocal<>();
	public static ThreadLocal<TDL_AddressChoosePage> TdlAddressOptChoose = new ThreadLocal<>();
	public static ThreadLocal<TDL_AddressPage> TdlAddresslist = new ThreadLocal<>();
	public static ThreadLocal<TDL_EnterAddressManuallyPage> TdlAddressManual = new ThreadLocal<>();
	public static ThreadLocal<TDL_GetCurrentLocationPage> TdlAddressGoogleLocation = new ThreadLocal<>();
	public static ThreadLocal<TDL_GoogleSearchAddressPage> TdlAddressGoogleSearch = new ThreadLocal<>();
	public static ThreadLocal<TDL_ReferaFriendPage> TdlReferAFriend = new ThreadLocal<>();
	public static ThreadLocal<TDL_ChangePasswordPage> TdlChangePassword = new ThreadLocal<>();
	public static ThreadLocal<TDL_LegalPage> TdlLegal = new ThreadLocal<>();
	public static ThreadLocal<TDL_ChangePasswordPage_Mobile> TdlChangePasswordPage_Mobile = new ThreadLocal<>();
	public static ThreadLocal<TDL_AddressPage_Mobile> TdlAddressPage_Mobile = new ThreadLocal<>();
	public static ThreadLocal<TDL_AddressChoosePage_Mobile> TdlAddressChoosePage_Mobile = new ThreadLocal<>();
	public static ThreadLocal<TDL_ReferNonTCPContactsPage_Mobile> TdlReferNonTCPContactsPage_Mobile = new ThreadLocal<>();
	public static ThreadLocal<TDL_ReferFriendPage_Mobile> TdlReferFriendPage_Mobile = new ThreadLocal<>();
	public static ThreadLocal<TDL_ProfilePage_Mobile> TdlProfilePage_Mobile = new ThreadLocal<>();
	public static ThreadLocal<TDL_EnterAddressManuallyPage_Mobile> TdlEnterAddressManuallyPage_Mobile = new ThreadLocal<>();
	public static ThreadLocal<TDL_GetCurrentLocationPage_Mobile> TdlGetCurrentLocationPage_Mobile = new ThreadLocal<>();
	public static ThreadLocal<TDL_GoogleSearchAddressPage_Mobile> TdlGoogleSearchAddressPage_Mobile = new ThreadLocal<>();
	public static ThreadLocal<TDL_CardProtectionJourneyPage> TdlCardProtectionJourneyPage = new ThreadLocal<>();
	public static ThreadLocal<TDL_HomeInsuranceJourneyPage> TdlHomeInsuranceJourneyPage = new ThreadLocal<>();
	public static ThreadLocal<TDL_FinancialServices_Mobile> TdlFinancialServices_Mobile = new ThreadLocal<>();
	public static ThreadLocal<TDL_HomeInsurancePage_Mobile> TdlHomeInsurancePage_Mobile = new ThreadLocal<>();
	public static ThreadLocal<PaymentCards> TdlPaymentCardPWA = new ThreadLocal<>();
	public static ThreadLocal<TDL_FSMyPlans_Mobile> TdlFSMyPlans_Mobile = new ThreadLocal<>();
	public static ThreadLocal<TDL_FSClaimsPage_Mobile> TdlFSClaimsPage_Mobile = new ThreadLocal<>();
	public static ThreadLocal<TDL_InsuranceCancellation_Mobile> TdlInsuranceCancellation_Mobile = new ThreadLocal<>();;
	public static ThreadLocal<TDL_PaymentCards_Mobile> TdlPaymentCards_Mobile = new ThreadLocal<>();
	public static ThreadLocal<TDL_InsuranceStatus_Mobile> TdlInsuranceStatus_Mobile = new ThreadLocal<>();
	public static ThreadLocal<TDL_MenuPage_Mobile> TdlMenuPage_Mobile = new ThreadLocal<>();
	public static ThreadLocal<TDL_FSUploadDocPage_Mobile> TdlFSUploadDocPage_Mobile = new ThreadLocal<>();
	public static ThreadLocal<TDL_FSDocUploadPage> TdlFSDocUploadPage = new ThreadLocal<>();
	public static ThreadLocal<TDL_OrderHistory_Mobile> TdlOrderHistory_Mobile = new ThreadLocal<>();
	public static ThreadLocal<TDL_OrderHistoryPage> TdlOrderHistoryPage = new ThreadLocal<>();
	public static ThreadLocal<TDL_OrderDetailsPage> TdlOrderDetailsPage = new ThreadLocal<>();
	public static ThreadLocal<TDL_CRM_DetailsPage> TDL_CRM_DetailsPage = new ThreadLocal<>();
	public static ThreadLocal<TDL_OrderDetails_Mobile> TdlOrderDetails_Mobile = new ThreadLocal<>();
	public static ThreadLocal<TDL_Channels_Mobile> TdlChannelsMobile = new ThreadLocal<>();
	public static ThreadLocal<TDL_ChannelsPage> TdlChannelsPage = new ThreadLocal<>();
	public static ThreadLocal<TDL_AccountTransferPage_Mobile> TdlAccountTransferPage_Mobile = new ThreadLocal<>();
	public static ThreadLocal<TDL_UPIRegistrationPage_Mobile> TdlUPIRegistrationPage_Mobile = new ThreadLocal<>();
	public static ThreadLocal<TDL_RequestMoneyPage_Mobile> TdlRequestMoneyPage_Mobile = new ThreadLocal<>();
	public static ThreadLocal<TDL_UPI_SettingsPage_Mobile> TdlUPI_SettingsPage_Mobile = new ThreadLocal<>();
	public static ThreadLocal<TDL_ManageBanksPage_Mobile> TdlManageBanksPage_Mobile = new ThreadLocal<>();
	public static ThreadLocal<TDL_ManageFavoritesPage_Mobile> TdlManageFavoritesPage_Mobile = new ThreadLocal<>();
	public static ThreadLocal<TDL_PayToSelfPage_Mobile> TdlPayToSelfPage_Mobile = new ThreadLocal<>();
	public static ThreadLocal<TDL_MATataSkyHomePage> TdlMATataSkyHomePage = new ThreadLocal<>();
	public static ThreadLocal<TDL_MABoxgradeHomePage> TdlMABoxgradeHomePage = new ThreadLocal<>();
	public static ThreadLocal<TDL_MAChannelsOptionPage> TdlMAChannelsOptionPage = new ThreadLocal<>();
	public static ThreadLocal<TDL_MAHDselectionPage> TdlMAHDselectionPage = new ThreadLocal<>();
	public static ThreadLocal<TDL_MANewConnectionPaymentsPage> TdlMANewConnectionPaymentsPage = new ThreadLocal<>();
	public static ThreadLocal<TDL_MAPaymentConnectionPage> TdlMAPaymentConnectionPage = new ThreadLocal<>();
	public static ThreadLocal<TDL_MAQuickRechargeHomePage> TdlMAQuickRechargeHomePage = new ThreadLocal<>();
	public static ThreadLocal<TDL_MAOPELPaymentsPage> TdlMAOPELPaymentsPage = new ThreadLocal<>();
	public static ThreadLocal<TDL_MARegisterPage> TdlMARegisterPage = new ThreadLocal<>();
	public static ThreadLocal<TDL_MASelectChannels> TdlMASelectChannels = new ThreadLocal<>();
	public static ThreadLocal<TDL_MASelectlanguagesPage> TdlMASelectlanguagesPage = new ThreadLocal<>();
	public static ThreadLocal<TDL_MAQuickRechargeOfferPage> TdlMAQuickRechargeOfferPage = new ThreadLocal<>();
	public static ThreadLocal<TDL_BP_RecentBillsAndCategoryPage_Mobile> TdlRecentBillsAndCategoryPage_Mobile = new ThreadLocal<>();
	public static ThreadLocal<TDL_BP_FetchBillAndBillersPage_Mobile> TdlFetchBillAndBillersPage_Mobile = new ThreadLocal<>();
	public static ThreadLocal<TDL_TataSkyRegisterPage_Mobile> tdlTataSkyRegisterPage_Mobile = new ThreadLocal<>();
	public static ThreadLocal<TDL_MASelectChannels_Mobile> tdlMASelectChannels_Mobile = new ThreadLocal<>();
	public static ThreadLocal<TDL_MASelectlanguagesPage_Mobile> tdlMASelectlanguagesPage_Mobile = new ThreadLocal<>();
	public static ThreadLocal<TDL_MAHDselectionPage_Mobile> tdlMAHDselectionPage_Mobile=new ThreadLocal<>();
    public static ThreadLocal<TDL_MANewConnectionPaymentsPage_Mobile>tdlMANewConnectionPaymentsPage_Mobile=new ThreadLocal<>();
    public static ThreadLocal<TDL_MACromaHomePage>TdlMACromaHomePage=new ThreadLocal<>();
    public static ThreadLocal<TDL_MACromaSearchProductPage>TdlMACromaSearchProductPage=new ThreadLocal<>();
    public static ThreadLocal<TDL_MAShowcasePage>TdlMAShowcasePage=new ThreadLocal<>();
    public static ThreadLocal<SwtTcpHomePage>SwtTcpHomePage=new ThreadLocal<>();
    public static ThreadLocal<SwtTcpHomePage_Mobile>SwtTcpHomePage_Mobile=new ThreadLocal<>();
    public static ThreadLocal<TDL_BP_Payments_Mobile> TdlBPPayments_Mobile = new ThreadLocal<>();
    public static ThreadLocal <TDL_LendingPage> TDL_LendingPage = new ThreadLocal<>();
	public static ThreadLocal <TDL_FSLendingPage_Mobile> TDLLending_Mobile = new ThreadLocal<>();
	public static ThreadLocal <TDL_TransactionPage> TDLTransaction_web = new ThreadLocal<>();
	public static ThreadLocal <TDL_Transaction_Mobile> TDLTransaction_Mobile = new ThreadLocal<>();
	public static ThreadLocal <TDL_UPI_TransHistoryPage_Mobile> TdlPaymentHistoryPage_Mobile = new ThreadLocal<>();
	public static ThreadLocal <TDL_ManageTransactionLimitPage_Mobile> TDLManageTransactionLimitPage_Mobile = new ThreadLocal<>();
	public static ThreadLocal <TDL_UPI_ApprovePage_Mobile> TdlUPIApprovePage_Mobile = new ThreadLocal<>();
	public static ThreadLocal <TDL_UPI_MandatePage_Mobile> TdlUPI_MandatePage_Mobile = new ThreadLocal<>();
	public static ThreadLocal<TDL_PayBillPage>tdlPayBill= new ThreadLocal<>();
	public static ThreadLocal<Qmin_CRM_Mobile_Element>QminCRM_Mobile_Element= new ThreadLocal<>();
	public static ThreadLocal<TDL_TataPayChannelPage_Mobile>TdlTataPayChannelPage_Mobile= new ThreadLocal<>();
	public static ThreadLocal<TDL_UniversalCartPage>TDL_UniversalCartPage= new ThreadLocal<>();
	public static ThreadLocal<TDL_UniversalCart_Mobile_Page>TDL_UniversalCart_Mobile_Page= new ThreadLocal<>();
	public static ThreadLocal<TDL_Capillary_API_Page> TDL_Capillary_APIPage = new ThreadLocal<>();
	public static ThreadLocal<TDL_CromaLoginPage> TDL_CromaLoginPage = new ThreadLocal<>();
	public static ThreadLocal<Gmail> gmailPage = new ThreadLocal<>();
	public static ThreadLocal<TDL_SLPElectronicsPage> TDL_SLPElectronicsPage = new ThreadLocal<>();
	public static ThreadLocal<TDL_SLPElectronicsPage_Mobile> TDL_SLPElectronicsPage_Mobile = new ThreadLocal<>();
	public static ThreadLocal<TDL_PersonalLoanPage> TDL_PersonalLoanPage = new ThreadLocal<>();
	public static ThreadLocal<TDL_MyQRPage_Mobile> TdlMyQRPage_Mobile = new ThreadLocal<>();
	public static ThreadLocal<MyAccount_TCPHomePage_Mobile> myAccount_TCPHomePage_Mobile = new ThreadLocal<>();
	public static ThreadLocal<TcpHomePageMyAccount> tcpHomePageMyAccount = new ThreadLocal<>();
	public static ThreadLocal<TDL_SSO> Tdl_SSO = new ThreadLocal<>();
	public static ThreadLocal<TDL_IHCLLoginPage> TDL_IHCLLoginPage = new ThreadLocal<>();
	public static ThreadLocal<NCOM_HomePage_Mobile> NCOM_HomePage_Mobile = new ThreadLocal<>();
	public static ThreadLocal<NCOM_Electronics_CLP_Page_Mobile> NCOM_Electronics_CLP_Page_Mobile = new ThreadLocal<>();
	public static ThreadLocal<NCOM_PDP_Page_Mobile> NCOM_PDP_Page_Mobile = new ThreadLocal<>();
	public static ThreadLocal<NCOM_PLP_Page_Mobile> NCOM_PLP_Page_Mobile = new ThreadLocal<>();
	public static ThreadLocal<NCOM_HomePage_Web> NCOM_HomePage_Web = new ThreadLocal<>();
	public static ThreadLocal<NCOM_Electronics_CLP_Web> NCOM_Electronics_CLP_Web = new ThreadLocal<>();
	public static ThreadLocal<NCOM_PDP_Web> NCOM_PDP_Web = new ThreadLocal<>();
	public static ThreadLocal<NCOM_PLP_Web> NCOM_PLP_Web = new ThreadLocal<>();
	public static ThreadLocal<NCOM_Cart_Page_Mobile> NCOM_Cart_Page_Mobile = new ThreadLocal<>();
	public static ThreadLocal<TCP_Performance> TCP_Performance = new ThreadLocal<>();
	public static ThreadLocal<TDL_SLPCultFit> TDL_SLPCultFit = new ThreadLocal<>();
	public static ThreadLocal<TDL_SLPCultFit_Mobile> TDL_SLPCultFit_Mobile = new ThreadLocal<>();
	public static ThreadLocal<TDL_SLPElectronics_FlutterPage_Mobile> TDL_SLPElectronics_FlutterPage_Mobile = new ThreadLocal<>();
	public static ThreadLocal<BB_TestCases>BB_TestCases = new ThreadLocal<>();
	public static ThreadLocal<Rewards_And_Benifits>Rewards_And_Benifits = new ThreadLocal<>();
	
	
    // web page
	public void initialisePageObjects(BrowserFactory browserFactory) {

		B2BLogin.set(PageFactory.initElements(browserFactory.getDriver(), B2BLogin.class));
		B2BPage2.set(PageFactory.initElements(browserFactory.getDriver(), B2BPage2.class));
		TdlSignUp.set(PageFactory.initElements(browserFactory.getDriver(), TDL_Signup.class));
		TdlHomePage.set(PageFactory.initElements(browserFactory.getDriver(), TDL_HomePage.class));
		TdlVaultPage.set(PageFactory.initElements(browserFactory.getDriver(), TDL_VaultPage.class));
		TdlTcpCard.set(PageFactory.initElements(browserFactory.getDriver(), TDL_TCPCardPage.class));
		TdlCromaCard.set(PageFactory.initElements(browserFactory.getDriver(), TDL_CromaCardPage.class));
		MyOffersPage.set(PageFactory.initElements(browserFactory.getDriver(), MyOffersPage.class));
		OfferDetailsPage.set(PageFactory.initElements(browserFactory.getDriver(), OfferDetailsPage.class));
		TdlAccountListPage.set(PageFactory.initElements(browserFactory.getDriver(), TDL_AccountListPage.class));
		TdlSearchPage.set(PageFactory.initElements(browserFactory.getDriver(), TDL_SearchPage.class));
		TdlIhclCard.set(PageFactory.initElements(browserFactory.getDriver(), TDL_IHCLCardPage.class));
		TdlPaymentsPage.set(PageFactory.initElements(browserFactory.getDriver(), TDL_PaymentsPage.class));
		TdlMultitenderPage.set(PageFactory.initElements(browserFactory.getDriver(), TDL_MultitenderPage.class));
		TdlTransactionStatus.set(PageFactory.initElements(browserFactory.getDriver(), TDL_TransactionStatus.class));
		TdlSecurePage.set(PageFactory.initElements(browserFactory.getDriver(), TDL_SecurePage.class));
		TdlAddCardPage.set(PageFactory.initElements(browserFactory.getDriver(), TDL_AddCardPage.class));
		TdlProfilePage.set(PageFactory.initElements(browserFactory.getDriver(), TDL_ProfilePage.class));
		TdlAddressOptChoose.set(PageFactory.initElements(browserFactory.getDriver(), TDL_AddressChoosePage.class));
		TdlAddresslist.set(PageFactory.initElements(browserFactory.getDriver(), TDL_AddressPage.class));
		TdlAddressManual.set(PageFactory.initElements(browserFactory.getDriver(), TDL_EnterAddressManuallyPage.class));
		TdlAddressGoogleLocation
				.set(PageFactory.initElements(browserFactory.getDriver(), TDL_GetCurrentLocationPage.class));
		TdlAddressGoogleSearch
				.set(PageFactory.initElements(browserFactory.getDriver(), TDL_GoogleSearchAddressPage.class));
		TdlReferAFriend.set(PageFactory.initElements(browserFactory.getDriver(), TDL_ReferaFriendPage.class));
		TdlChangePassword.set(PageFactory.initElements(browserFactory.getDriver(), TDL_ChangePasswordPage.class));
		TdlLegal.set(PageFactory.initElements(browserFactory.getDriver(), TDL_LegalPage.class));
		TdlCardProtectionJourneyPage
				.set(PageFactory.initElements(browserFactory.getDriver(), TDL_CardProtectionJourneyPage.class));
		TdlHomeInsuranceJourneyPage
				.set(PageFactory.initElements(browserFactory.getDriver(), TDL_HomeInsuranceJourneyPage.class));
		TdlPaymentCardPWA.set(PageFactory.initElements(browserFactory.getDriver(), PaymentCards.class));
		TdlFSDocUploadPage.set(PageFactory.initElements(browserFactory.getDriver(), TDL_FSDocUploadPage.class));
		TdlOrderHistoryPage.set(PageFactory.initElements(browserFactory.getDriver(), TDL_OrderHistoryPage.class));
		TdlOrderDetailsPage.set(PageFactory.initElements(browserFactory.getDriver(), TDL_OrderDetailsPage.class));
		TDL_CRM_DetailsPage.set(PageFactory.initElements(browserFactory.getDriver(), TDL_CRM_DetailsPage.class));
		TdlMATataSkyHomePage.set(PageFactory.initElements(browserFactory.getDriver(), TDL_MATataSkyHomePage.class));
		TdlMABoxgradeHomePage.set(PageFactory.initElements(browserFactory.getDriver(), TDL_MABoxgradeHomePage.class));
		TdlMAChannelsOptionPage.set(PageFactory.initElements(browserFactory.getDriver(), TDL_MAChannelsOptionPage.class));
		TdlMAHDselectionPage.set(PageFactory.initElements(browserFactory.getDriver(), TDL_MAHDselectionPage.class));
		TdlMANewConnectionPaymentsPage
				.set(PageFactory.initElements(browserFactory.getDriver(), TDL_MANewConnectionPaymentsPage.class));
		TdlMAPaymentConnectionPage
				.set(PageFactory.initElements(browserFactory.getDriver(), TDL_MAPaymentConnectionPage.class));
		TdlMAQuickRechargeHomePage
				.set(PageFactory.initElements(browserFactory.getDriver(), TDL_MAQuickRechargeHomePage.class));
		TdlMAOPELPaymentsPage.set(PageFactory.initElements(browserFactory.getDriver(), TDL_MAOPELPaymentsPage.class));
		TdlMARegisterPage.set(PageFactory.initElements(browserFactory.getDriver(), TDL_MARegisterPage.class));
		TdlMASelectChannels.set(PageFactory.initElements(browserFactory.getDriver(), TDL_MASelectChannels.class));
		TdlMASelectlanguagesPage
				.set(PageFactory.initElements(browserFactory.getDriver(), TDL_MASelectlanguagesPage.class));
		TdlMAQuickRechargeOfferPage
				.set(PageFactory.initElements(browserFactory.getDriver(), TDL_MAQuickRechargeOfferPage.class));
		TdlChannelsPage
		.set(PageFactory.initElements(browserFactory.getDriver(), TDL_ChannelsPage.class));
		TdlMACromaHomePage.set(PageFactory.initElements(browserFactory.getDriver(), TDL_MACromaHomePage.class));
		TdlMACromaSearchProductPage.set(PageFactory.initElements(browserFactory.getDriver(), TDL_MACromaSearchProductPage.class));
		TdlMAShowcasePage.set(PageFactory.initElements(browserFactory.getDriver(), TDL_MAShowcasePage.class));
		SwtTcpHomePage.set(PageFactory.initElements(browserFactory.getDriver(),SwtTcpHomePage.class));
		TDL_LendingPage.set(PageFactory.initElements(browserFactory.getDriver(), TDL_LendingPage.class));
		TDLTransaction_web.set(PageFactory.initElements(browserFactory.getDriver(), TDL_TransactionPage.class));
		tdlPayBill.set(PageFactory.initElements(browserFactory.getDriver(), TDL_PayBillPage.class));
		TDL_UniversalCartPage.set(PageFactory.initElements(browserFactory.getDriver(), TDL_UniversalCartPage.class));
		TDL_Capillary_APIPage.set(PageFactory.initElements(browserFactory.getDriver(), TDL_Capillary_API_Page.class));
		TDL_CromaLoginPage.set(PageFactory.initElements(browserFactory.getDriver(), TDL_CromaLoginPage.class));
		gmailPage.set(PageFactory.initElements(browserFactory.getDriver(), Gmail.class));
		TDL_SLPElectronicsPage.set(PageFactory.initElements(browserFactory.getDriver(), TDL_SLPElectronicsPage.class));
		TDL_PersonalLoanPage.set(PageFactory.initElements(browserFactory.getDriver(), TDL_PersonalLoanPage.class));
		Tdl_SSO.set(PageFactory.initElements(browserFactory.getDriver(), TDL_SSO.class));
		tcpHomePageMyAccount.set(PageFactory.initElements(browserFactory.getDriver(), TcpHomePageMyAccount.class));
		TDL_IHCLLoginPage.set(PageFactory.initElements(browserFactory.getDriver(), TDL_IHCLLoginPage.class));
		NCOM_HomePage_Web.set(PageFactory.initElements(browserFactory.getDriver(), NCOM_HomePage_Web.class));
		NCOM_Electronics_CLP_Web.set(PageFactory.initElements(browserFactory.getDriver(), NCOM_Electronics_CLP_Web.class));
		NCOM_PDP_Web.set(PageFactory.initElements(browserFactory.getDriver(), NCOM_PDP_Web.class));
		NCOM_PLP_Web.set(PageFactory.initElements(browserFactory.getDriver(), NCOM_PLP_Web.class));
		TCP_Performance.set(PageFactory.initElements(browserFactory.getDriver(), TCP_Performance.class));
		TDL_SLPCultFit.set(PageFactory.initElements(browserFactory.getDriver(), TDL_SLPCultFit.class));
	}

	// for mobile page
	public void initialisePageObjects() {
		// CalcPage=PageFactory.initElements(new
		// AppiumFieldDecorator(BaseScript.appiumDriver), CalcPage.class);
		// CalcPage=PageFactory.initElements(BaseScript.appiumDriver, CalcPage.class);
		CalcPage.set(new CalcPage());
		TdlSignUpMobile.set(new TDL_Signup_Mobile());
		MyOffers_Mobile.set(new MyOffers_Mobile());
		TdlHomeMobile.set(new TDL_HomePage_Mobile());
		TdlVaultMobile.set(new TDL_VaultPage_Mobile());
		TdlTCPCardMobile.set(new TDL_TCPCardPage_Mobile());
		TdlCromaCardMobile.set(new TDL_CromaCardPage_Mobile());
		TdlSearchPage_Mobile.set(new TDL_SearchPage_Mobile());
		TdlAccountListPage_Mobile.set(new TDL_AccountListPage_Mobile());
		TdlAddCardPage_Mobile.set(new TDL_AddCardPage_Mobile());
		TdlSecurePage_Mobile.set(new TDL_SecurePage_Mobile());
		TdlMultitenderPage_Mobile.set(new TDL_MultitenderPage_Mobile());
		TdlPaymentsPage_Mobile.set(new TDL_PaymentsPage_Mobile());
		TdlTransactionStatus_Mobile.set(new TDL_TransactionStatus_Mobile());
		TdlOtherPage_Mobile.set(new TDL_OtherPage_Mobile());
		TdlChangePasswordPage_Mobile.set(new TDL_ChangePasswordPage_Mobile());
		TdlAddressPage_Mobile.set(new TDL_AddressPage_Mobile());
		TdlAddressChoosePage_Mobile.set(new TDL_AddressChoosePage_Mobile());
		TdlReferNonTCPContactsPage_Mobile.set(new TDL_ReferNonTCPContactsPage_Mobile());
		TdlReferFriendPage_Mobile.set(new TDL_ReferFriendPage_Mobile());
		TdlProfilePage_Mobile.set(new TDL_ProfilePage_Mobile());
		TdlEnterAddressManuallyPage_Mobile.set(new TDL_EnterAddressManuallyPage_Mobile());
		TdlGetCurrentLocationPage_Mobile.set(new TDL_GetCurrentLocationPage_Mobile());
		TdlGoogleSearchAddressPage_Mobile.set(new TDL_GoogleSearchAddressPage_Mobile());
		TdlFinancialServices_Mobile.set(new TDL_FinancialServices_Mobile());
		TdlHomeInsurancePage_Mobile.set(new TDL_HomeInsurancePage_Mobile());
		TDLPaymentMethodPage_Mobile.set(new TDL_PaymentMethodPage_Mobile());
		TdlFSMyPlans_Mobile.set(new TDL_FSMyPlans_Mobile());
		TdlFSClaimsPage_Mobile.set(new TDL_FSClaimsPage_Mobile());
		TdlInsuranceCancellation_Mobile.set(new TDL_InsuranceCancellation_Mobile());
		TdlPaymentCards_Mobile.set(new TDL_PaymentCards_Mobile());
		TdlInsuranceStatus_Mobile.set(new TDL_InsuranceStatus_Mobile());
		TdlMenuPage_Mobile.set(new TDL_MenuPage_Mobile());
		TdlFSUploadDocPage_Mobile.set(new TDL_FSUploadDocPage_Mobile());
		TdlOrderHistory_Mobile.set(new TDL_OrderHistory_Mobile());
		TdlOrderDetails_Mobile.set(new TDL_OrderDetails_Mobile());
		TdlChannelsMobile.set(new TDL_Channels_Mobile());
		TdlAccountTransferPage_Mobile.set(new TDL_AccountTransferPage_Mobile());
		TdlUPIRegistrationPage_Mobile.set(new TDL_UPIRegistrationPage_Mobile());
		TdlRequestMoneyPage_Mobile.set(new TDL_RequestMoneyPage_Mobile());
		TdlUPI_SettingsPage_Mobile.set(new TDL_UPI_SettingsPage_Mobile());
		TdlManageBanksPage_Mobile.set(new TDL_ManageBanksPage_Mobile());
		TdlManageFavoritesPage_Mobile.set(new TDL_ManageFavoritesPage_Mobile());
		TdlPayToSelfPage_Mobile.set(new TDL_PayToSelfPage_Mobile());
		TdlRecentBillsAndCategoryPage_Mobile.set(new TDL_BP_RecentBillsAndCategoryPage_Mobile());
		TdlFetchBillAndBillersPage_Mobile.set(new TDL_BP_FetchBillAndBillersPage_Mobile());
		tdlTataSkyRegisterPage_Mobile.set(new TDL_TataSkyRegisterPage_Mobile());
		tdlMASelectlanguagesPage_Mobile.set(new TDL_MASelectlanguagesPage_Mobile());
		tdlMASelectChannels_Mobile.set(new TDL_MASelectChannels_Mobile());
		tdlMANewConnectionPaymentsPage_Mobile.set(new TDL_MANewConnectionPaymentsPage_Mobile());
		SwtTcpHomePage_Mobile.set(new SwtTcpHomePage_Mobile());
		TdlBPPayments_Mobile.set(new TDL_BP_Payments_Mobile());
		TDLLending_Mobile .set( new TDL_FSLendingPage_Mobile());
		TDLTransaction_Mobile.set( new TDL_Transaction_Mobile());
		TdlPaymentHistoryPage_Mobile.set( new TDL_UPI_TransHistoryPage_Mobile());
		TDLManageTransactionLimitPage_Mobile.set( new TDL_ManageTransactionLimitPage_Mobile());
		TdlUPIApprovePage_Mobile.set( new TDL_UPI_ApprovePage_Mobile());
		TdlUPI_MandatePage_Mobile.set(new TDL_UPI_MandatePage_Mobile());
		QminCRM_Mobile_Element.set(new Qmin_CRM_Mobile_Element());
		TdlTataPayChannelPage_Mobile.set(new TDL_TataPayChannelPage_Mobile());
		TDL_UniversalCart_Mobile_Page.set(new TDL_UniversalCart_Mobile_Page());
		TDL_SLPElectronicsPage_Mobile.set(new TDL_SLPElectronicsPage_Mobile());
		TdlMyQRPage_Mobile.set(new TDL_MyQRPage_Mobile());
		myAccount_TCPHomePage_Mobile.set(new MyAccount_TCPHomePage_Mobile());
		NCOM_HomePage_Mobile.set(new NCOM_HomePage_Mobile());
		NCOM_Electronics_CLP_Page_Mobile.set(new NCOM_Electronics_CLP_Page_Mobile());
		NCOM_PLP_Page_Mobile.set(new NCOM_PLP_Page_Mobile());
		NCOM_PDP_Page_Mobile.set(new NCOM_PDP_Page_Mobile());
		NCOM_Cart_Page_Mobile.set(new NCOM_Cart_Page_Mobile());
		TDL_SLPCultFit_Mobile.set(new TDL_SLPCultFit_Mobile());
		TDL_SLPElectronics_FlutterPage_Mobile.set(new TDL_SLPElectronics_FlutterPage_Mobile());
		BB_TestCases.set(new BB_TestCases());
		Rewards_And_Benifits.set(new Rewards_And_Benifits());
	}
}